version: '3'
services:
  backend:
    build: backend
    depends_on:
      - database
      - graph
    restart: unless-stopped
    environment:
      - PORT=8000
      - MAX_WORKERS=10
      - POSTGRES_URI=artgas:artgas@database:5432/artgas
      - NEO4J_URI=neo4j://graph:7687
      - AVATAR_DATA_FOLDER=_data/avatar-data
      - POSTGRES_MIN_POOL_SIZE=1
      - POSTGRES_MAX_POOL_SIZE=5
      - JWT_SECRET=secret
    ports:
      - "8000:8000"
    expose:
      - 8000
    command: bash -c "python wait_for.py && python init_db.py && uvicorn main:app --host 0.0.0.0 --port 8000 --workers $${MAX_WORKERS}"
    volumes:
      - "./_data/avatar-data:/app/_data/avatar-data"
  database:
    image: "postgres:13.3-alpine"
    restart: unless-stopped
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=artgas
      - POSTGRES_USER=artgas
      - POSTGRES_DB=artgas
    volumes:
      - ./_data/postgres-data:/var/lib/postgresql/data
  graph:
    image: "neo4j:4.3.2-community"
    restart: unless-stopped
    expose:
      - 7474
      - 7687
    environment:
      - NEO4J_AUTH=neo4j/secret
    volumes:
      - ./_data/neo4j-data:/data

