version: '3'
services:
  database:
    image: "postgres:13.3-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=artgas
      - POSTGRES_USER=artgas
      - POSTGRES_DB=artgas
    volumes:
      - ./_data-dev/postgres-data:/var/lib/postgresql/data
  graph:
    image: "neo4j:4.3.2-community"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/secret
    volumes:
      - ./_data-dev/neo4j-data:/data
