version: '3'
services:
  database:
    image: "postgres:13.3-alpine"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=artgas
      - POSTGRES_USER=artgas
      - POSTGRES_DB=artgas
  graph:
    image: "neo4j:4.3.2-community"
    ports:
      - "7475:7474"
      - "7688:7687"
    environment:
      - NEO4J_AUTH=neo4j/secret
